<?php
session_start();
include "includes/library.inc.php";
include "includes/sql_connect.php";
select_forms();
head_std("Rules - Team List");
body_top();
echo "<script type=\"text/javascript\" src=\"includes/wz_tooltip.js\"></script>";
echo "<div align=center>\n";
echo "<table border=1 cellspacing=0 cellpadding=0 width=800>";
	echo "<tr><td>\n";
	echo "<table cellspacing=0 cellpadding=0>";
		echo "<tr>";
		echo "<td align=center width=400><B>TEAMS</B></a></td>\n";
		echo "<td width=400 align=center>\n";
		echo "<table border=1 cellspacing=0 cellpadding=0 width=400>\n";
			echo "<tr><td align=center>\n";
			echo "<a href=rules_skills.php><B>SKILLS</B></a>\n";
			echo "</td></tr>\n";
		echo "</table>\n</td>\n";
		echo "</tr>\n";
		echo "<tr><td colspan=2>\n";
		rules_teams();
		echo "</td></tr>\n";
	echo "</table>/n";
	echo "</td></tr>\n";
echo "</table>/n";
echo "</div>";
echo "</body>\n</html>";
?>